# Generated by Django 4.2.6 on 2023-10-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='user_id',
            new_name='user',
        ),
    ]
