# Generated by Django 4.2.6 on 2023-10-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_options_rename_team_id_teammember_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
