# Generated by Django 4.2.6 on 2023-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_photo'),
        ('teams', '0004_alter_teammember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(null=True, to='users.user'),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
