# Generated by Django 4.2.6 on 2023-10-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_direction_alter_user_faculty_and_more'),
        ('teams', '0005_team_members_delete_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_teams', to='users.user'),
        ),
    ]
