# Generated by Django 4.2.6 on 2023-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_cropped_photo_alter_user_photo'),
        ('teams', '0006_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
