# Generated by Django 4.2.6 on 2023-10-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_alter_direction_code_alter_direction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(),
        ),
    ]
