# Generated by Django 4.2.6 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_e_mail_user_phone_number_user_photo_user_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/users_photos'),
        ),
    ]
