# Generated by Django 4.2.6 on 2023-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
