# Generated by Django 4.2.6 on 2023-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_members_delete_teammember'),
        ('users', '0014_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(null=True, to='teams.team'),
        ),
    ]
