# Generated by Django 4.2.6 on 2023-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_direction_alter_user_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cropped_photo',
            field=models.ImageField(blank=True, default='images/default_user_photo.png', upload_to='images/users_photos'),
        ),
    ]
