# Generated by Django 4.2.6 on 2023-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_members'),
        ('users', '0020_alter_user_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='teams.team'),
        ),
    ]
