# Generated by Django 4.2.6 on 2024-03-30 19:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cropped_photo',
            field=models.ImageField(blank=True, default='images/cropped-default-user-photo.png', upload_to=users.models.get_cropped_photo_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-user-photo.png', upload_to=users.models.get_photo_path),
        ),
    ]
