# Generated by Django 4.2.6 on 2023-10-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='images/default_user_photo.png', upload_to='images/projects_photos'),
        ),
    ]
