# Generated by Django 4.2.6 on 2023-10-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_direction_alter_user_faculty_and_more'),
        ('teams', '0005_team_members_delete_teammember'),
        ('projects', '0005_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcolumn',
            name='column',
        ),
        migrations.RemoveField(
            model_name='projectcolumn',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_projects', to='users.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_projects', to='teams.team'),
        ),
    ]
