# Generated by Django 4.2.6 on 2023-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_column_delete_projectcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('в работе', 'в работе'), ('приостановлен', 'приостановлен'), ('завершен', 'завершен')], null=True),
        ),
    ]
