# Generated by Django 4.2.6 on 2023-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('в работе', 'в работе'), ('приостановлен', 'приостановлен'), ('завершен', 'завершен')], max_length=20, null=True),
        ),
    ]
