# Generated by Django 4.2.6 on 2023-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='images/project_default.png', upload_to='images/projects_photos'),
        ),
    ]
