# Generated by Django 4.2.6 on 2023-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technical_task',
            field=models.FileField(blank=True, null=True, upload_to='projects_tech_tasks'),
        ),
    ]
