# Generated by Django 4.2.6 on 2023-11-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_members'),
        ('projects', '0012_alter_project_technical_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('в работе', 'в работе'), ('приостановлен', 'приостановлен'), ('завершен', 'завершен')], default='в работе', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_projects', to='teams.team'),
        ),
    ]
