# Generated by Django 4.2.6 on 2024-03-29 19:20

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='images/project-default-photo.png', upload_to=projects.models.get_photo_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_task',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.get_technical_task_path),
        ),
    ]
