# Generated by Django 4.2.6 on 2023-10-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=50, choices=[('срочно', 'срочно'), ('не срочно', 'не срочно')])),
                ('status', models.CharField(max_length=50, choices=[('назначена', 'назначена'), ('в процессе', 'в процессе'), ('выполнена', 'выполнена')])),
                ('creation_datetime', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('appointed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_task_set', to='users.user')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_task_set', to='users.user')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
