# Generated by Django 4.2.6 on 2023-10-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectcolumn_column_and_more'),
        ('users', '0016_alter_user_direction_alter_user_faculty_and_more'),
        ('tasks', '0003_alter_task_options_rename_column_id_task_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.AlterField(
            model_name='task',
            name='appointed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_tasks', to='users.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_tasks', to='users.user'),
        ),
    ]
