# Generated by Django 4.2.6 on 2023-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_column_alter_task_appointed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=20, choices=[('назначена', 'назначена'), ('в работе', 'в работе'), ('выполнена', 'выполнена')], null=True),
        ),
    ]
