# Generated by Django 4.2.6 on 2024-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_creation_datetime_task_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
