# Generated by Django 4.2.6 on 2023-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_account_options_rename_user_id_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(unique=True),
        ),
    ]
