# Generated by Django 4.2.6 on 2023-10-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_account_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
